{% set name = "molpipeline" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molpipeline-{{ version }}.tar.gz
  sha256: 2998526be0c2aa56568645abb620ad53a9b704f86e859a03998cd57cc891ac1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - joblib >=1.3.0
    - loguru
    - numpy
    - pandas
    - rdkit >=2023.9.1
    - scipy
    - setuptools
    - scikit-learn >=1.4.0
    - typing-extensions

test:
  imports:
    - molpipeline
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Integration of rdkit functionality into sklearn pipelines.
  home: https://github.com/basf/MolPipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
