{% set name = "molpipeline" %}
{% set version = "0.10.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molpipeline-{{ version }}.tar.gz
  sha256: bcac5f6f9351653549458c7be3877d994af1b7857fc3fcfbdaeb616fb17074a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - matplotlib-base >=3.10.1
    - shap >=0.47.1
    - typing_extensions >=4.13.1
    - python >={{ python_min }}
    - joblib >=1.3.0
    - loguru >=0.7.3
    - numpy >=1.26.4
    - pandas >=2.2.3
    - rdkit >=2023.9.1
    - scipy >=1.15.2
    - setuptools
    - scikit-learn >=1.6.0
    - typing-extensions

test:
  imports:
    - molpipeline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Integration of rdkit functionality into sklearn pipelines.
  home: https://github.com/basf/MolPipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
