{% set name = "molpipeline" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molpipeline-{{ version }}.tar.gz
  sha256: 097e50a3c62a6935592c9461b3020a227aed05922d281e1589821227d884adc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - matplotlib-base
    - shap
    - typing_extensions
    - python >={{ python_min }}
    - joblib >=1.3.0
    - loguru
    - numpy
    - pandas
    - rdkit >=2023.9.1
    - scipy
    - setuptools
    - scikit-learn >=1.6.0
    - typing-extensions

test:
  imports:
    - molpipeline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Integration of rdkit functionality into sklearn pipelines.
  home: https://github.com/basf/MolPipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
